"use client";

import {
  Accessibility, AlertCircle, ArrowRight, Building2, CalendarDays, Car,
  CheckCircle2, ChevronDown, Clock3, FileText, HeartPulse, Hospital,
  Languages, MapPin, Menu, Phone, Search, ShieldCheck, Stethoscope,
  Trash2, UserRound, Vote, X,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type PortalKind = "dmv" | "hospital" | "county";
type TextSize = "standard" | "large" | "extra-large";
type Contrast = "standard" | "high";
type Spacing = "standard" | "relaxed";
type NavMode = "standard" | "simplified";
type Experience = { textSize: TextSize; contrast: Contrast; spacing: Spacing; navigation: NavMode; plainLanguage: boolean; reducedMotion: boolean; focusTask: string | null };

const defaults: Experience = { textSize: "standard", contrast: "standard", spacing: "standard", navigation: "standard", plainLanguage: false, reducedMotion: false, focusTask: null };
const tasks = {
  dmv: ["renew-license", "renew-registration", "replace-license", "schedule-appointment"],
  hospital: ["find-urgent-care", "find-doctor", "schedule-visit", "pay-bill"],
  county: ["pay-property-tax", "find-trash-day", "register-to-vote", "apply-for-permit"],
};
const toolResult = (text: string) => ({ content: [{ type: "text", text }] });

function registerExperienceTools(kind: PortalKind, getExperience: () => Experience, update: (changes: Partial<Experience>) => void, reset: () => void) {
  const modelContext = (document as Document & { modelContext?: { registerTool: (tool: Record<string, unknown>) => void; unregisterTool?: (name: string) => void } }).modelContext;
  if (!modelContext?.registerTool) return () => {};
  const registered: string[] = [];
  const add = (tool: Record<string, unknown> & { name: string }) => { modelContext.registerTool(tool); registered.push(tool.name) };

  add({ name: "get_experience_capabilities", description: "List the safe interface adaptations this website supports for the current visitor.", inputSchema: { type: "object", properties: {} }, annotations: { readOnlyHint: true }, execute: async () => toolResult(JSON.stringify({ site: kind, supported: ["text-size", "contrast", "spacing", "plain-language", "reduced-motion", "simplified-navigation", "task-focus"], availableTasks: tasks[kind] })) });
  add({ name: "inspect_experience", description: "Read the visitor's current interface settings and task focus on this website.", inputSchema: { type: "object", properties: {} }, annotations: { readOnlyHint: true }, execute: async () => toolResult(JSON.stringify({ site: kind, ...getExperience() })) });
  add({ name: "set_readability", description: "Adjust text size, contrast, spacing, plain language, or motion to make the website easier to use.", inputSchema: { type: "object", properties: { textSize: { type: "string", enum: ["standard", "large", "extra-large"] }, contrast: { type: "string", enum: ["standard", "high"] }, spacing: { type: "string", enum: ["standard", "relaxed"] }, plainLanguage: { type: "boolean" }, reducedMotion: { type: "boolean" } } }, annotations: { readOnlyHint: false }, execute: async (input: Partial<Experience>) => { update(input); return toolResult("Readability preferences applied to the current website.") } });
  add({ name: "set_navigation_mode", description: "Switch between the full site navigation and a simplified navigation with only essential actions.", inputSchema: { type: "object", properties: { mode: { type: "string", enum: ["standard", "simplified"] } }, required: ["mode"] }, annotations: { readOnlyHint: false }, execute: async ({ mode }: { mode: NavMode }) => { update({ navigation: mode }); return toolResult(`Navigation is now ${mode}.`) } });
  add({ name: "focus_on_task", description: "Reorganize this website around one supported task and remove unrelated content from the main flow.", inputSchema: { type: "object", properties: { task: { type: "string", enum: tasks[kind] } }, required: ["task"] }, annotations: { readOnlyHint: false }, execute: async ({ task }: { task: string }) => { update({ focusTask: task, navigation: "simplified" }); return toolResult(`The page is now focused on ${task.replaceAll("-", " ")}.`) } });
  add({ name: "apply_preference_profile", description: "Apply a reusable visitor preference profile using this website's supported design controls.", inputSchema: { type: "object", properties: { profile: { type: "string", enum: ["low-vision", "reduced-distraction", "comfortable-reading"] } }, required: ["profile"] }, annotations: { readOnlyHint: false }, execute: async ({ profile }: { profile: string }) => { const profiles: Record<string, Partial<Experience>> = { "low-vision": { textSize: "extra-large", contrast: "high", spacing: "relaxed", navigation: "simplified", reducedMotion: true }, "reduced-distraction": { navigation: "simplified", spacing: "relaxed", reducedMotion: true }, "comfortable-reading": { textSize: "large", spacing: "relaxed", plainLanguage: true } }; update(profiles[profile] ?? {}); return toolResult(`${profile.replaceAll("-", " ")} preferences applied using this site's own interface controls.`) } });
  add({ name: "reset_experience", description: "Restore the website's standard interface and remove any active task focus.", inputSchema: { type: "object", properties: {} }, annotations: { readOnlyHint: false }, execute: async () => { reset(); return toolResult("The website has been restored to its standard experience.") } });
  return () => registered.forEach((name) => modelContext.unregisterTool?.(name));
}

const linkSets = {
  dmv: ["Driver Services", "Vehicle Services", "Appointments", "Locations", "Forms"],
  hospital: ["Find Care", "Patients & Visitors", "Services", "Locations", "About Us"],
  county: ["Government", "Departments", "Residents", "Business", "How Do I?"],
};

function NetworkBar({ kind }: { kind: PortalKind }) {
  return <div className="network-bar"><div className="site-width network-inner"><span>Local services</span><div>{kind !== "dmv" && <a href="/">Carolina DMV</a>}{kind !== "hospital" && <a href="/hospital">Piedmont Regional Health</a>}{kind !== "county" && <a href="/county">Oak County</a>}</div></div></div>;
}

function Brand({ kind }: { kind: PortalKind }) {
  if (kind === "dmv") return <div className="brand"><div className="dmv-mark"><Car size={25} /></div><div><b>Carolina</b><span>Department of Motor Vehicles</span></div></div>;
  if (kind === "hospital") return <div className="brand hospital-brand"><div className="health-mark"><HeartPulse size={27} /></div><div><b>Piedmont Regional</b><span>Health System</span></div></div>;
  return <div className="brand"><div className="county-seal">OC</div><div><b>Oak County</b><span>North Carolina</span></div></div>;
}

function Header({ kind, simplified, onOptions }: { kind: PortalKind; simplified: boolean; onOptions: () => void }) {
  return <><NetworkBar kind={kind}/>{kind === "hospital" && <div className="emergency-strip"><div className="site-width"><b>Medical emergency?</b> Call 911. <a href="#care">Find urgent care</a></div></div>}<header className="main-header"><div className="site-width header-row"><Brand kind={kind}/><div className="header-actions"><button className="display-button" onClick={onOptions}><Accessibility size={19}/> Display options</button><button className="portal-button"><UserRound size={17}/>{kind === "hospital" ? "Patient portal" : kind === "county" ? "MyOak account" : "MyDMV"}</button></div></div><nav className="primary-nav" aria-label="Main navigation"><div className="site-width nav-row">{(simplified ? linkSets[kind].slice(0, 2) : linkSets[kind]).map((link)=><a href="#services" key={link}>{link}</a>)}{!simplified && <a href="#contact">Contact</a>}<button aria-label="Search"><Search size={20}/><span>Search</span></button><button className="mobile-menu"><Menu size={22}/><span>Menu</span></button></div></nav></header></>;
}

const focusContent: Record<PortalKind, Record<string, { eyebrow: string; title: string; copy: string; steps: string[]; action: string }>> = {
  dmv: {
    "renew-license": { eyebrow: "Driver license renewal", title: "Renew your driver license", copy: "Most drivers can renew online in about 10 minutes. Have your current license and payment method ready.", steps: ["Confirm you are eligible", "Verify your information", "Pay the renewal fee"], action: "Start online renewal" },
    "renew-registration": { eyebrow: "Vehicle registration", title: "Renew your vehicle registration", copy: "Use the plate number and title number shown on your renewal notice.", steps: ["Enter vehicle details", "Review taxes and fees", "Pay and receive confirmation"], action: "Renew registration" },
    "replace-license": { eyebrow: "Lost or damaged license", title: "Order a replacement license", copy: "Request a duplicate license online. It will be mailed to the address on file.", steps: ["Verify your identity", "Confirm mailing address", "Pay the replacement fee"], action: "Order replacement" },
    "schedule-appointment": { eyebrow: "DMV office visit", title: "Schedule an appointment", copy: "Choose a service, location and available time before visiting an office.", steps: ["Choose your service", "Find a nearby office", "Select a date and time"], action: "Find appointments" },
  },
  hospital: {
    "find-urgent-care": { eyebrow: "Care you can get today", title: "Find urgent care near you", copy: "See nearby clinics, current hours and estimated wait times. For a life-threatening emergency, call 911.", steps: ["Share your ZIP code", "Compare open locations", "Reserve a visit time"], action: "View urgent care locations" },
    "find-doctor": { eyebrow: "Find a provider", title: "Choose the right doctor", copy: "Search by specialty, location, insurance and appointment availability.", steps: ["Tell us the care you need", "Review matched providers", "Request an appointment"], action: "Search doctors" },
    "schedule-visit": { eyebrow: "Appointments", title: "Schedule a visit", copy: "Existing patients can schedule many visits online through the patient portal.", steps: ["Sign in securely", "Choose your provider", "Select an available time"], action: "Schedule in patient portal" },
    "pay-bill": { eyebrow: "Billing", title: "Pay your medical bill", copy: "Make a secure payment using the account number on your statement. A portal account is not required.", steps: ["Enter statement details", "Review your balance", "Submit secure payment"], action: "Pay a bill" },
  },
  county: {
    "pay-property-tax": { eyebrow: "Tax administration", title: "Pay your property tax bill", copy: "Search by owner name, address or parcel number, then pay securely online.", steps: ["Find your property", "Review the amount due", "Choose a payment method"], action: "Search and pay taxes" },
    "find-trash-day": { eyebrow: "Solid waste services", title: "Find your collection day", copy: "Enter your address to see trash, recycling and yard waste pickup dates.", steps: ["Enter your home address", "View the collection schedule", "Save pickup reminders"], action: "Check my address" },
    "register-to-vote": { eyebrow: "Board of elections", title: "Register to vote", copy: "Check eligibility, download the registration form and find submission options.", steps: ["Check your eligibility", "Complete the registration form", "Submit by the deadline"], action: "Start voter registration" },
    "apply-for-permit": { eyebrow: "Planning and development", title: "Apply for a building permit", copy: "Start an application, upload plans and track review status online.", steps: ["Choose the permit type", "Prepare required documents", "Submit your application"], action: "Start permit application" },
  },
};

function FocusPanel({ kind, task, onReset }: { kind: PortalKind; task: string; onReset: () => void }) {
  const content = focusContent[kind][task]; if (!content) return null;
  return <main className="focus-main"><div className="site-width"><div className="preference-note"><CheckCircle2 size={18}/><span>This page has been simplified around your task.</span><button onClick={onReset}>Show full site</button></div><section className="focus-card"><p className="eyebrow">{content.eyebrow}</p><h1>{content.title}</h1><p className="lead">{content.copy}</p><ol className="task-steps">{content.steps.map((step,i)=><li key={step}><span>{i+1}</span><b>{step}</b></li>)}</ol><button className="primary-action">{content.action}<ArrowRight size={19}/></button><div className="help-row"><Phone size={18}/><span>Need help? Call <b>1-800-555-0148</b>, Monday–Friday, 8 a.m.–5 p.m.</span></div></section></div></main>;
}

function DmvHome() {
  const services = [[Car,"Renew a registration","Renew online and print your receipt"],[FileText,"Renew a driver license","Check eligibility and renewal options"],[CalendarDays,"Schedule an appointment","Choose an office, service and time"],[MapPin,"Find a DMV office","Hours, services and current wait times"]] as const;
  return <main><section className="dmv-alert"><div className="site-width"><AlertCircle size={20}/><div><b>REAL ID deadline information</b><span>Learn what documents to bring before visiting a DMV office.</span></div><a href="#">View requirements <ArrowRight size={16}/></a></div></section><section className="dmv-hero"><div className="site-width hero-grid"><div><p className="eyebrow">Official services for Carolina drivers</p><h1>How can we help today?</h1><p>Complete common driver and vehicle services online, or prepare for your visit to a DMV office.</p><div className="service-search"><Search size={21}/><input aria-label="Search DMV services" placeholder="Search licenses, registration, titles and more"/><button>Search</button></div></div><div className="renew-card"><span>Skip the office</span><h2>Renew online in minutes</h2><p>Many driver licenses and vehicle registrations can be renewed from home.</p><button>Check my eligibility <ArrowRight size={18}/></button></div></div></section><section className="site-width service-section" id="services"><div className="section-heading"><div><p className="eyebrow">Popular services</p><h2>Get it done online</h2></div><a href="#">View all services <ArrowRight size={17}/></a></div><div className="service-grid">{services.map(([Icon,title,copy])=><a className="service-card" href="#" key={title}><Icon size={27}/><div><h3>{title}</h3><p>{copy}</p></div><ArrowRight className="card-arrow" size={19}/></a>)}</div></section><section className="dmv-info"><div className="site-width info-grid"><div><Clock3/><h3>Office wait times</h3><p>See estimated wait times before you leave home.</p><a href="#">Check wait times</a></div><div><ShieldCheck/><h3>REAL ID</h3><p>Find out whether you need one and what to bring.</p><a href="#">Get REAL ID ready</a></div><div><FileText/><h3>Forms and manuals</h3><p>Download official forms and driver handbooks.</p><a href="#">Browse forms</a></div></div></section></main>;
}

function HospitalHome() {
  return <main><section className="hospital-hero"><div className="site-width hospital-hero-inner"><div><p className="eyebrow">Care for every stage of life</p><h1>Exceptional care, close to home.</h1><p>From everyday wellness to advanced specialty care, our teams are here for you and your family.</p><div className="hero-buttons"><button>Find a doctor <ArrowRight size={18}/></button><button className="outline-button">Find a location</button></div></div><div className="care-finder" id="care"><h2>How can we care for you?</h2><button><Stethoscope/><span><b>Find a doctor</b><small>Search by specialty or name</small></span><ArrowRight/></button><button><Clock3/><span><b>Urgent care</b><small>See locations and wait times</small></span><ArrowRight/></button><button><CalendarDays/><span><b>Schedule an appointment</b><small>New and current patients</small></span><ArrowRight/></button></div></div></section><section className="site-width hospital-actions" id="services"><a href="#"><CalendarDays/><b>Schedule care</b><span>Book an appointment</span></a><a href="#"><UserRound/><b>Patient portal</b><span>Messages, results and visits</span></a><a href="#"><FileText/><b>Pay a bill</b><span>Secure online payment</span></a><a href="#"><Phone/><b>Contact us</b><span>Get the right help</span></a></section><section className="site-width specialties"><p className="eyebrow">Our specialties</p><h2>Expert care when you need it</h2><div className="specialty-grid"><article><HeartPulse/><h3>Heart & vascular</h3><p>Complete cardiovascular care, from prevention to recovery.</p><a href="#">Explore heart care <ArrowRight/></a></article><article><Hospital/><h3>Children&apos;s care</h3><p>Compassionate primary and specialty care for children.</p><a href="#">Explore children&apos;s care <ArrowRight/></a></article><article><Stethoscope/><h3>Primary care</h3><p>Trusted care for checkups, illness and long-term health.</p><a href="#">Find primary care <ArrowRight/></a></article></div></section><section className="health-note"><div className="site-width"><div><p className="eyebrow">Piedmont Regional Medical Center</p><h2>Recognized for safe, high-quality care</h2><p>Our physicians, nurses and staff work together to put every patient first.</p></div><div className="quality-stat"><b>24/7</b><span>Emergency care</span></div><div className="quality-stat"><b>40+</b><span>Care locations</span></div></div></section></main>;
}

function CountyHome() {
  const services = [[FileText,"Pay property taxes","View bills and make a payment"],[Trash2,"Trash & recycling","Schedules, carts and collection help"],[Building2,"Permits & inspections","Apply, pay fees and track status"],[Vote,"Voting & elections","Registration, polling places and results"],[MapPin,"Parks & recreation","Programs, facilities and reservations"],[ShieldCheck,"Public safety","Sheriff, fire and emergency updates"]] as const;
  return <main><section className="county-alert"><div className="site-width"><span>County notice</span><p>Board of Commissioners public hearing scheduled for September 8 at 6 p.m.</p><a href="#">Meeting details <ArrowRight/></a></div></section><section className="county-hero"><div className="site-width"><p className="eyebrow">Welcome to Oak County</p><h1>Services for residents, businesses and visitors</h1><div className="county-search"><Search/><input aria-label="Search county services" placeholder="What can we help you find?"/><button>Search</button></div><div className="trending"><b>Popular:</b><a href="#">Property taxes</a><a href="#">Job openings</a><a href="#">Building permits</a><a href="#">Trash pickup</a></div></div></section><section className="site-width county-services" id="services"><div className="section-heading"><div><p className="eyebrow">County services</p><h2>How can we help?</h2></div><a href="#">View all departments <ArrowRight/></a></div><div className="county-grid">{services.map(([Icon,title,copy])=><a href="#" key={title}><span><Icon/></span><div><h3>{title}</h3><p>{copy}</p></div><ArrowRight className="card-arrow"/></a>)}</div></section><section className="county-news"><div className="site-width news-grid"><div><p className="eyebrow">Latest from Oak County</p><h2>News and updates</h2><article><span>September 1, 2026</span><h3>Oak County opens applications for small business improvement grants</h3><a href="#">Read the announcement <ArrowRight/></a></article></div><aside><CalendarDays/><p className="eyebrow">Upcoming meeting</p><h3>Board of Commissioners</h3><p>Tuesday, September 8<br/>6:00 p.m.</p><a href="#">View agenda</a></aside></div></section></main>;
}

function OptionsPanel({ value, onChange, onClose, onReset }: { value: Experience; onChange: (v: Partial<Experience>) => void; onClose: () => void; onReset: () => void }) {
  return <div className="options-overlay" role="presentation" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><aside className="options-panel" role="dialog" aria-modal="true" aria-label="Display options"><div className="options-header"><div><Accessibility/><h2>Display options</h2></div><button onClick={onClose} aria-label="Close display options"><X/></button></div><p>Adjust this site to make it more comfortable for you to use.</p><fieldset><legend>Text size</legend><div className="segmented">{(["standard","large","extra-large"] as TextSize[]).map((size)=><button className={value.textSize===size?"active":""} onClick={()=>onChange({textSize:size})} key={size}>{size === "extra-large" ? "Extra large" : size[0].toUpperCase()+size.slice(1)}</button>)}</div></fieldset><fieldset><legend>Reading preferences</legend><label><input type="checkbox" checked={value.contrast==="high"} onChange={(e)=>onChange({contrast:e.target.checked?"high":"standard"})}/><span>High contrast</span></label><label><input type="checkbox" checked={value.spacing==="relaxed"} onChange={(e)=>onChange({spacing:e.target.checked?"relaxed":"standard"})}/><span>More spacing</span></label><label><input type="checkbox" checked={value.plainLanguage} onChange={(e)=>onChange({plainLanguage:e.target.checked})}/><span>Plain language</span></label><label><input type="checkbox" checked={value.navigation==="simplified"} onChange={(e)=>onChange({navigation:e.target.checked?"simplified":"standard"})}/><span>Simplified navigation</span></label><label><input type="checkbox" checked={value.reducedMotion} onChange={(e)=>onChange({reducedMotion:e.target.checked})}/><span>Reduce motion</span></label></fieldset><button className="reset-button" onClick={onReset}>Restore standard display</button></aside></div>;
}

function Footer({ kind }: { kind: PortalKind }) {
  return <footer id="contact"><div className="site-width footer-grid"><Brand kind={kind}/><div><b>Contact</b><a href="#">Call 1-800-555-0148</a><a href="#">Send a message</a><a href="#">Find a location</a></div><div><b>Resources</b><a href="#">Accessibility</a><a href="#">Privacy</a><a href="#">Languages</a></div><div><b>Language</b><button><Languages/> English <ChevronDown/></button></div></div><div className="site-width footer-bottom">© 2026 {kind === "dmv" ? "Carolina Department of Motor Vehicles" : kind === "hospital" ? "Piedmont Regional Health System" : "Oak County Government"}</div></footer>;
}

export function Portal({ kind }: { kind: PortalKind }) {
  const [experience, setExperience] = useState<Experience>(defaults); const [optionsOpen, setOptionsOpen] = useState(false); const [loaded, setLoaded] = useState(false);
  useEffect(()=>{ try { const saved=localStorage.getItem("adaptive-web-preferences"); if(saved) setExperience({ ...defaults, ...JSON.parse(saved), focusTask:null }) } catch {} setLoaded(true) },[]);
  const update=(changes:Partial<Experience>)=>setExperience((current)=>{ const next={...current,...changes}; try { localStorage.setItem("adaptive-web-preferences",JSON.stringify({...next,focusTask:null})) } catch {} return next });
  const reset=()=>{ setExperience(defaults); try { localStorage.removeItem("adaptive-web-preferences") } catch {} };
  useEffect(()=>registerExperienceTools(kind,()=>experience,update,reset),[kind,experience]);
  const active=useMemo(()=>Object.entries(experience).some(([key,value])=>key==="focusTask"?Boolean(value):value!==defaults[key as keyof Experience]),[experience]);
  return <div className={`portal portal-${kind}`} data-text={experience.textSize} data-contrast={experience.contrast} data-spacing={experience.spacing} data-motion={experience.reducedMotion?"reduced":"standard"}><Header kind={kind} simplified={experience.navigation==="simplified"} onOptions={()=>setOptionsOpen(true)}/>{active&&!experience.focusTask&&loaded&&<div className="active-preferences"><div className="site-width"><CheckCircle2/><span>Your display preferences are active.</span><button onClick={reset}>Restore standard display</button></div></div>}{experience.focusTask?<FocusPanel kind={kind} task={experience.focusTask} onReset={reset}/>:kind==="dmv"?<DmvHome/>:kind==="hospital"?<HospitalHome/>:<CountyHome/>}<Footer kind={kind}/>{optionsOpen&&<OptionsPanel value={experience} onChange={update} onClose={()=>setOptionsOpen(false)} onReset={reset}/>}</div>;
}
